// <auto-generated />
using Chroma.Infrastructure.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Chroma.Infrastructure.Migrations
{
    [DbContext(typeof(ChromaDbContext))]
    [Migration("20250930091451_AddPaletteEntity")]
    partial class AddPaletteEntity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Chroma.Domain.Entities.Palette", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Palettes");
                });

            modelBuilder.Entity("Chroma.Domain.Entities.Palette", b =>
                {
                    b.OwnsMany("Chroma.Domain.ValueObjects.Color", "Colors", b1 =>
                        {
                            b1.Property<long>("PaletteColorId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bigint");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<long>("PaletteColorId"));

                            b1.Property<int>("BluePigment")
                                .HasColumnType("int")
                                .HasColumnName("B");

                            b1.Property<int>("GreenPigment")
                                .HasColumnType("int")
                                .HasColumnName("G");

                            b1.Property<decimal>("Opacity")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("A");

                            b1.Property<long>("PaletteId")
                                .HasColumnType("bigint");

                            b1.Property<int>("RedPigment")
                                .HasColumnType("int")
                                .HasColumnName("R");

                            b1.HasKey("PaletteColorId");

                            b1.HasIndex("PaletteId");

                            b1.ToTable("PaletteColors", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("PaletteId");
                        });

                    b.Navigation("Colors");
                });
#pragma warning restore 612, 618
        }
    }
}
