global using Dapper;
global using CleanArchitecture.Infrastructure.DataAccess;
global using CleanArchitecture.Infrastructure.DataAccess.EntityConfigurations;
global using CleanArchitecture.Infrastructure.DataAccess.QueryServices;
global using CleanArchitecture.Infrastructure.DataAccess.Repositories;